version: '3.4'

services:
  demo_webapp:
    restart: "no"
    image: ubuntu/supervisord:1 
    ports:
    - "81:80"
    environment:
    - TZ=UTC
    networks:
      ADSL:
        ipv4_address: 172.30.0.19
    volumes:
      - '/opt/proyecto/storage/demo_webapp:/var/www/html'
    

  demo_api_app_v2:
    restart: "no" 
    image: apps/api_dev:1
    ports:
      - "80:80"
    environment:
      - TZ=UTC
    networks:
      ADSL:
        ipv4_address: 172.30.0.20
    volumes:
      - '/opt/proyecto/storage/demo_api_app:/var/www/html' 


  demo_api_db:
    image: 'bitnami/postgresql:14'
    ports:
      - '5432:5432'
    environment:
      - TZ=UTC
      - POSTGRESQL_DATABASE=conversiones_peso
      - POSTGRESQL_USERNAME=conversiones_proy
      - POSTGRESQL_PASSWORD=12345proy
    networks:
      ADSL:
         ipv4_address: 172.30.1.20   
    volumes:
      - 'demo_api_db_data:/bitnami/postgresql'


  demo_login_db:
    image: 'bitnami/postgresql:14'
    ports:
      - '5431:5432'
    environment:
      - TZ=UTC
      - POSTGRESQL_DATABASE=proyecto_login
      - POSTGRESQL_USERNAME=users_login
      - POSTGRESQL_PASSWORD=mjk12345
    networks:
      ADSL:
         ipv4_address: 172.30.1.21  
    volumes:
      - 'demo_login_db_data:/bitnami/postgresql'

networks:
  ADSL:
    external: true

volumes:
    demo_api_db_data:
      driver: local 
    demo_webapp:
      driver: local
    demo_login_db_data:
      driver: local 

